name: rlhf-lesson
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch>=2.0.0
  - numpy>=1.21.0
  - matplotlib>=3.5.0
  - scikit-learn>=1.0.0
  - pandas>=1.3.0
  - seaborn>=0.11.0
  - jupyter>=1.0.0
  - notebook>=6.4.0
  - pip
  - pip:
    - transformers>=4.20.0
    - trl>=0.7.0
    - accelerate>=0.20.0
    - datasets>=2.10.0
    - ipykernel
    - nb_conda_kernels
