name: vision-lesson
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - numpy>=1.21.0
  - matplotlib>=3.5.0
  - scipy>=1.7.0
  - scikit-learn>=1.0.0
  - pandas>=1.3.0
  - seaborn>=0.11.0
  - jupyter>=1.0.0
  - notebook>=6.4.0
  - opencv>=4.5.0
  - pillow>=8.0.0
  - pip
  - pip:
    - transformers>=4.20.0
    - einops>=0.6.0
    - ipykernel
    - nb_conda_kernels
